### PR TITLE
HtbQueue: Fix HtbScheduler trying to dequeue from invalid input queues

### PR DESCRIPTION
**Pull request by m-bosk**
After recent restructuring of our internal experiments and update of the simulation environment to OMNeT++ 6.0 with INET4.4 (and inet-gpl), we ran across an issue while trying to use the HtbQueue and associated modules. The fingerprint tests for htb yielded the following results (excerpt):
```
 % ./fingerprinttest --debug -m htb
/examples/htb/ -f omnetpp.ini -c scenarioTCP3 -r 0  ... : ERROR (should be PASS): runtime error with exitcode=1: <!> Error: Scheduled packet from invalid input gate: -1 -- in module (inetgpl::queueing::HtbScheduler) htbEvaluation.hostFDO[0].ppp[0].queue.scheduler (id=37), at t=1s, event #6
/examples/htb/ -f omnetpp.ini -c scenarioTCP2 -r 0  ... : ERROR (should be PASS): runtime error with exitcode=1: <!> Error: Scheduled packet from invalid input gate: -1 -- in module (inetgpl::queueing::HtbScheduler) htbEvaluation.hostFDO[0].ppp[0].queue.scheduler (id=43), at t=1s, event #9
/examples/htb/ -f omnetpp.ini -c scenarioUDP3 -r 0  ... : ERROR (should be PASS): runtime error with exitcode=1: <!> Error: Scheduled packet from invalid input gate: -1 -- in module (inetgpl::queueing::HtbScheduler) htbEvaluation.serverFDO.ppp[0].queue.scheduler (id=84), at t=1s, event #11
/examples/htb/ -f omnetpp.ini -c scenarioUDP4 -r 0  ... : ERROR (should be PASS): runtime error with exitcode=1: <!> Error: Scheduled packet from invalid input gate: -1 -- in module (inetgpl::queueing::HtbScheduler) htbEvaluation.serverFDO.ppp[0].queue.scheduler (id=96), at t=1s, event #20
/examples/htb/ -f omnetpp.ini -c scenarioUDP2 -r 0  ... : ERROR (should be PASS): runtime error with exitcode=1: <!> Error: Scheduled packet from invalid input gate: -1 -- in module (inetgpl::queueing::HtbScheduler) htbEvaluation.serverFDO.ppp[0].queue.scheduler (id=96), at t=1s, event #20
/examples/htb/ -f omnetpp.ini -c scenarioUDP1 -r 0  ... : ERROR (should be PASS): runtime error with exitcode=1: <!> Error: Scheduled packet from invalid input gate: -1 -- in module (inetgpl::queueing::HtbScheduler) htbEvaluation.serverFDO.ppp[0].queue.scheduler (id=96), at t=1s, event #20
/examples/htb/ -f omnetpp.ini -c scenarioTCP1 -r 0  ... : ERROR (should be PASS): runtime error with exitcode=1: <!> Error: Scheduled packet from invalid input gate: -1 -- in module (inetgpl::queueing::HtbScheduler) htbEvaluation.hostFDO[0].ppp[0].queue.scheduler (id=43), at t=1s, event #9
/examples/htb/ -f omnetpp.ini -c scenarioUDP4Eth -r 0  ... : ERROR (should be PASS): runtime error with exitcode=1: <!> Error: Scheduled packet from invalid input gate: -1 -- in module (inetgpl::queueing::HtbScheduler) htbEvaluationEth.serverFDO.eth[0].queue.scheduler (id=98), at t=1s, event #21
<!> Error: Scheduled packet from invalid input gate: -1 -- in module (inetgpl::queueing::HtbScheduler) htbEvaluationEth.serverFDO.eth[0].queue.scheduler (id=98), during network cleanup
<!> Error: ASSERT: Condition 'componentv[i]->isChannel() && componentv[i]->getParentModule()==nullptr' does not hold in function 'deleteNetwork' at csimulation.cc:468 -- during network cleanup
/examples/htb/ -f omnetpp.ini -c scenarioUDP3Eth -r 0  ... : ERROR (should be PASS): runtime error with exitcode=1: <!> Error: Scheduled packet from invalid input gate: -1 -- in module (inetgpl::queueing::HtbScheduler) htbEvaluationEth.serverFDO.eth[0].queue.scheduler (id=86), at t=1s, event #12
<!> Error: Scheduled packet from invalid input gate: -1 -- in module (inetgpl::queueing::HtbScheduler) htbEvaluationEth.serverFDO.eth[0].queue.scheduler (id=86), during network cleanup
<!> Error: ASSERT: Condition 'componentv[i]->isChannel() && componentv[i]->getParentModule()==nullptr' does not hold in function 'deleteNetwork' at csimulation.cc:468 -- during network cleanup
/examples/htb/ -f omnetpp.ini -c scenarioTCP1Eth -r 0  ... : ERROR (should be PASS): runtime error with exitcode=1: <!> Error: Scheduled packet from invalid input gate: -1 -- in module (inetgpl::queueing::HtbScheduler) htbEvaluationEth.hostFDO[0].eth[0].queue.scheduler (id=44), at t=1s, event #10
<!> Error: Scheduled packet from invalid input gate: -1 -- in module (inetgpl::queueing::HtbScheduler) htbEvaluationEth.hostFDO[0].eth[0].queue.scheduler (id=44), during network cleanup
<!> Error: ASSERT: Condition 'componentv[i]->isChannel() && componentv[i]->getParentModule()==nullptr' does not hold in function 'deleteNetwork' at csimulation.cc:468 -- during network cleanup
/examples/htb/ -f omnetpp.ini -c scenarioUDP2Eth -r 0  ... : ERROR (should be PASS): runtime error with exitcode=1: <!> Error: Scheduled packet from invalid input gate: -1 -- in module (inetgpl::queueing::HtbScheduler) htbEvaluationEth.serverFDO.eth[0].queue.scheduler (id=98), at t=1s, event #21
<!> Error: Scheduled packet from invalid input gate: -1 -- in module (inetgpl::queueing::HtbScheduler) htbEvaluationEth.serverFDO.eth[0].queue.scheduler (id=98), during network cleanup
<!> Error: ASSERT: Condition 'componentv[i]->isChannel() && componentv[i]->getParentModule()==nullptr' does not hold in function 'deleteNetwork' at csimulation.cc:468 -- during network cleanup
/examples/htb/ -f omnetpp.ini -c scenarioUDP1Eth -r 0  ... : ERROR (should be PASS): runtime error with exitcode=1: <!> Error: Scheduled packet from invalid input gate: -1 -- in module (inetgpl::queueing::HtbScheduler) htbEvaluationEth.serverFDO.eth[0].queue.scheduler (id=98), at t=1s, event #21
<!> Error: Scheduled packet from invalid input gate: -1 -- in module (inetgpl::queueing::HtbScheduler) htbEvaluationEth.serverFDO.eth[0].queue.scheduler (id=98), during network cleanup
<!> Error: ASSERT: Condition 'componentv[i]->isChannel() && componentv[i]->getParentModule()==nullptr' does not hold in function 'deleteNetwork' at csimulation.cc:468 -- during network cleanup
/examples/htb/ -f omnetpp.ini -c scenarioTCP4 -r 0  ... : ERROR (should be PASS): runtime error with exitcode=1: <!> Error: Scheduled packet from invalid input gate: -1 -- in module (inetgpl::queueing::HtbScheduler) htbEvaluation.hostFDO[0].ppp[0].queue.scheduler (id=43), at t=1s, event #9
/examples/htb/ -f omnetpp.ini -c scenarioTCP2Eth -r 0  ... : ERROR (should be PASS): runtime error with exitcode=139: <!> Error: Scheduled packet from invalid input gate: -1 -- in module (inetgpl::queueing::HtbScheduler) htbEvaluationEth.hostFDO[0].eth[0].queue.scheduler (id=44), at t=1s, event #10
<!> Error: Scheduled packet from invalid input gate: -1 -- in module (inetgpl::queueing::HtbScheduler) htbEvaluationEth.hostFDO[0].eth[0].queue.scheduler (id=44), during network cleanup
/examples/htb/ -f omnetpp.ini -c scenarioTCP3Eth -r 0  ... : ERROR (should be PASS): runtime error with exitcode=1: <!> Error: Scheduled packet from invalid input gate: -1 -- in module (inetgpl::queueing::HtbScheduler) htbEvaluationEth.hostFDO[0].eth[0].queue.scheduler (id=38), at t=1s, event #7
<!> Error: Scheduled packet from invalid input gate: -1 -- in module (inetgpl::queueing::HtbScheduler) htbEvaluationEth.hostFDO[0].eth[0].queue.scheduler (id=38), during network cleanup
<!> Error: ASSERT: Condition 'componentv[i]->isChannel() && componentv[i]->getParentModule()==nullptr' does not hold in function 'deleteNetwork' at csimulation.cc:468 -- during network cleanup
/examples/htb/ -f omnetpp.ini -c scenarioTCP4Eth -r 0  ... : ERROR (should be PASS): runtime error with exitcode=1: <!> Error: Scheduled packet from invalid input gate: -1 -- in module (inetgpl::queueing::HtbScheduler) htbEvaluationEth.hostFDO[0].eth[0].queue.scheduler (id=44), at t=1s, event #10
<!> Error: Scheduled packet from invalid input gate: -1 -- in module (inetgpl::queueing::HtbScheduler) htbEvaluationEth.hostFDO[0].eth[0].queue.scheduler (id=44), during network cleanup
<!> Error: ASSERT: Condition 'componentv[i]->isChannel() && componentv[i]->getParentModule()==nullptr' does not hold in function 'deleteNetwork' at csimulation.cc:468 -- during network cleanup

...

----------------------------------------------------------------------
Ran 16 tests in 6.174s

FAILED (errors=16)

Check examples.csv.ERROR for errors
Log has been saved to test.out
Test results differ from expected results
```

As can be seen, the HtbScheduler was trying to schedule packets from invalid input gates.

It turns out that the method `HtbScheduler::getNumPackets()` was returning that packets were available for dequeuing, despite none of the htb classes being active on any priority. Our assumption is that this happens now due to some change in the INET4.4 version which tries to check immediately after a packet is pushed to the queue whether there are packets available for dequeue and then indirectly calls the htbDequeue method. However, we were unable to pinpoint the exact change that introduced the issue.

More exactly the problem is that `HtbScheduler::getNumPackets()` returns that there are packets available to dequeue, despite all leaf classes being inactive (i.e. not knowing that packets are in their queues, cause the `HtbScheduler::htbEnqueue(int index)` has not been called for them yet). That leads to htbDequeue being called immediately afterwards (without ever executing htbEnqueue), which cannot find any valid leaf to dequeue (since all are inactive).

The fix for this issue comes with this pull request. We implement an additional check within the `HtbScheduler::getNumPackets()` method that verifies whether a leaf class with packets in associated queue has also been activated on any priority (otherwise the scheduling wouldn't be able to dequeue packets).

Furthermore, we update the fingerprint tests (after verifying that the actual results are still correct):
```
% ./fingerprinttest -m htb
/examples/htb/ -f omnetpp.ini -c scenarioTCP3 -r 0  ... : PASS
/examples/htb/ -f omnetpp.ini -c scenarioUDP3 -r 0  ... : PASS
/examples/htb/ -f omnetpp.ini -c scenarioTCP2 -r 0  ... : PASS
/examples/htb/ -f omnetpp.ini -c scenarioTCP1 -r 0  ... : PASS
/examples/htb/ -f omnetpp.ini -c scenarioTCP4 -r 0  ... : PASS
/examples/htb/ -f omnetpp.ini -c scenarioUDP3Eth -r 0  ... : PASS
/examples/htb/ -f omnetpp.ini -c scenarioUDP2 -r 0  ... : PASS
/examples/htb/ -f omnetpp.ini -c scenarioUDP4 -r 0  ... : PASS
/examples/htb/ -f omnetpp.ini -c scenarioUDP1 -r 0  ... : PASS
/examples/htb/ -f omnetpp.ini -c scenarioTCP3Eth -r 0  ... : PASS
/examples/htb/ -f omnetpp.ini -c scenarioTCP1Eth -r 0  ... : PASS
/examples/htb/ -f omnetpp.ini -c scenarioTCP2Eth -r 0  ... : PASS
/examples/htb/ -f omnetpp.ini -c scenarioTCP4Eth -r 0  ... : PASS
/examples/htb/ -f omnetpp.ini -c scenarioUDP1Eth -r 0  ... : PASS
/examples/htb/ -f omnetpp.ini -c scenarioUDP2Eth -r 0  ... : PASS
/examples/htb/ -f omnetpp.ini -c scenarioUDP4Eth -r 0  ... : PASS

----------------------------------------------------------------------
Ran 16 tests in 38.888s

OK

Log has been saved to test.out
Test results equals to expected results
```

### CODE REVIEW

**Comment by levy** [comment]
Thanks! This looks very good, I'll take a look at this later today. I knew this was broken and wanted to get back to you to make it work. The first version of the INET-GPL project will be released after every test PASSES.

**Comment by levy** [comment]
One quick question though. Do you know why did the tNl fingerprints change? I'm asking because this one only depends on the time and length of packets exchanged between network nodes. Shouldn't they stay the same?

**Comment by m-bosk** [comment]
Not sure why the tNI fingerprints changed. 

Different reporting of the number of available packets by `HtbScheduler::getNumPackets()` with this commit might have changed the behaviour of HTB slightly. Still, the general functionality (based on the evaluation of htb examples results) shows the correct and expected functionality of the module.

Also, other changes in INET 4.4 might have changed how HtbScheduler interacts with the rest of the framework? Really not sure here...

Another guess could be that not checking if the classes are active while calculating how many packets are available to be dequeued might also have been a bug before that only just now showed. The above mentioned case only really happens when the queue was empty and a packet was pushed to a queue. So in the end, the behaviour of HtbScheduler cannot change much with this adjustment.

That said, all of the above are more of guesses as to what might have happened.

**Comment by levy** [comment]
That's fine. Since you carefully analyzed the behavior by hand, I think this should be accepted. This was the case in the first place, so it's not likely that it's worse than it was before and fingerprint testing is useful if we want to save the time spent on careful manual analysis.

**Pull request merged**
